Server run at localhost:8081
Server run at localhost:443
我正在执行py脚本，稍等
进来了
开始写文件
文件写入成功
开始写文件
文件写入成功
Traceback (most recent call last):
  File "setence_motion_cls/bert_predict.py", line 3, in <module>
    import bert_init
ModuleNotFoundError: No module named 'bert_init'
Server run at localhost:443
我正在执行py脚本，稍等
我正在执行py脚本，稍等
我正在执行py脚本，稍等
进来了
我正在执行py脚本，稍等
我正在执行py脚本，稍等
进来了
进来了
我正在执行py脚本，稍等
我正在执行py脚本，稍等
我正在执行py脚本，稍等
我正在执行py脚本，稍等
我正在执行py脚本，稍等
我正在执行py脚本，稍等
我正在执行py脚本，稍等
我正在执行py脚本，稍等
我正在执行py脚本，稍等
我正在执行py脚本，稍等
我正在执行py脚本，稍等
我正在执行py脚本，稍等
我正在执行py脚本，稍等
